/**
 * Mapa de iconos del Design System (FASE-01).
 *
 * Lucide es el ÚNICO set de iconos (DS readme: 2px stroke, currentColor). Para
 * conservar la API de nombres en kebab-case que ya usa todo el código y el
 * prototipo (`<Icon name="map-pin" />`), mapeamos cada nombre al componente
 * Lucide correspondiente. Importar por nombre permite tree-shaking (solo entran
 * al bundle los iconos realmente usados), a diferencia del registry completo.
 *
 * Para añadir un icono nuevo: impórtalo de `lucide-react` y agrégalo aquí.
 */
import type { ComponentType, SVGProps } from 'react';
import {
  AlertCircle,
  AlertOctagon,
  Activity,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownCircle,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  BarChart2,
  Bell,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  CalendarX,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  CornerUpLeft,
  CreditCard,
  DollarSign,
  Download,
  Edit,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Home,
  Inbox,
  Info,
  LayoutGrid,
  Link,
  List,
  Lock,
  LogOut,
  Mail,
  MessageCircle,
  MapPin,
  Minus,
  MessageSquare,
  MoreHorizontal,
  MoreVertical,
  Navigation,
  Package,
  Pause,
  Percent,
  PieChart,
  Phone,
  Play,
  Plus,
  Power,
  RefreshCw,
  Repeat,
  RotateCcw,
  Scissors,
  Search,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Smartphone,
  Sparkles,
  Star,
  Store,
  Terminal,
  Ticket,
  TrendingUp,
  Trash2,
  User,
  UserPlus,
  UserX,
  Users,
  Wallet,
  X,
  XCircle,
  Zap,
} from 'lucide-react';

export type LucideComp = ComponentType<SVGProps<SVGSVGElement> & { size?: number | string }>;

/** Nombre kebab-case → componente Lucide. */
export const ICONS: Record<string, LucideComp> = {
  'alert-circle': AlertCircle,
  'alert-octagon': AlertOctagon,
  'alert-triangle': AlertTriangle,
  archive: Archive,
  'arrow-down': ArrowDown,
  'arrow-down-circle': ArrowDownCircle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'bar-chart-2': BarChart2,
  bell: Bell,
  briefcase: Briefcase,
  building: Building,
  'building-2': Building2,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  'calendar-x': CalendarX,
  activity: Activity,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  clock: Clock,
  copy: Copy,
  'corner-up-left': CornerUpLeft,
  'credit-card': CreditCard,
  'dollar-sign': DollarSign,
  download: Download,
  edit: Edit,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-text': FileText,
  filter: Filter,
  home: Home,
  inbox: Inbox,
  info: Info,
  'layout-grid': LayoutGrid,
  link: Link,
  list: List,
  lock: Lock,
  'log-out': LogOut,
  mail: Mail,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  minus: Minus,
  'more-horizontal': MoreHorizontal,
  'more-vertical': MoreVertical,
  navigation: Navigation,
  package: Package,
  pause: Pause,
  percent: Percent,
  'pie-chart': PieChart,
  phone: Phone,
  play: Play,
  plus: Plus,
  power: Power,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  'rotate-ccw': RotateCcw,
  scissors: Scissors,
  search: Search,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  star: Star,
  smartphone: Smartphone,
  store: Store,
  terminal: Terminal,
  ticket: Ticket,
  'trending-up': TrendingUp,
  'trash-2': Trash2,
  user: User,
  'user-plus': UserPlus,
  'user-x': UserX,
  users: Users,
  wallet: Wallet,
  x: X,
  'x-circle': XCircle,
  zap: Zap,
};
